<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th colspan=3>Action</th>
    </tr>

    <?php
    $collection = $block->getResult();
    foreach ($collection as $item) {
        ?>
    <tr>
        <td><?php echo $item->getData('id'); ?></td>
        <td><?php echo $item->getData('name'); ?></td>
        <td><?php echo $item->getData('created_at'); ?></td>
        <td><?php echo $item->getData('updated_at'); ?></td>
        <td><a href="<?php echo $block->getUrl('mymodule/index/insert'); ?>" class="action primary">Add</a></td>
        <td><a href="<?php echo $block->getUrl('mymodule/index/edit') . 'id/' . $item->getData('id'); ?>" class="action primary">Edit</a></td>
        <td><a href="<?php echo $block->getUrl('mymodule/index/delete') . 'id/' . $item->getData('id'); ?>" class="action primary">Delete</a></td>
    </tr>
    <?php
    }
    ?>
</table>
